
namespace Core
{
    public class Packets
    {

        // Packets sent by client to server
        public enum ClientPackets
        {
            CLogin,
            CRegister,
            CAddChar,
            CUseChar,
            CDelChar,
            CSayMsg,
            CBroadcastMsg,
            CPlayerMsg,
            CAdminMsg,
            CPlayerMove,
            CPlayerDir,
            CUseItem,
            CAttack,
            CPlayerInfoRequest,
            CWarpMeTo,
            CWarpToMe,
            CWarpTo,
            CSetSprite,
            CGetStats,
            CRequestNewMap,
            CNeedMap,
            CKickPlayer,
            CBanList,
            CBanDestroy,
            CBanPlayer,

            CSetAccess,
            CWhosOnline,
            CSetMotd,
            CSearch,
            CSkills,
            CCast,
            CQuit,
            CSwapInvSlots,
            CSwapSkillSlots,

            CCheckPing,
            CUnequip,
            CTrainStat,
            
            CRequestSkill,
            CRequestShop,
            CRequestLevelUp,
            CForgetSkill,
            CCloseShop,
            CBuyItem,
            CSellItem,
            CChangeBankSlots,
            CDepositItem,
            CWithdrawItem,
            CCloseBank,
            CAdminWarp,
            CTradeInvite,
            CHandleTradeInvite,
            CAcceptTrade,
            CDeclineTrade,
            CTradeItem,
            CUntradeItem,
            CAdmin,
            CSetHotbarSlot,
            CDeleteHotbarSlot,
            CUseHotbarSlot,

            CRequestProjectile,
            CClearProjectile,
            CEmote,
            CRequestParty,
            CAcceptParty,
            CDeclineParty,
            CLeaveParty,
            CPartyChatMsg,

            // *************************
            // ***   EDITOR PACKETS  ***
            // *************************
            CMapRespawn,
            CMapReport,
            CSaveMap,
            CSkillLearn,
            
            // Make sure COUNT is below everything else
            Count
        }

        // Packets sent by server to client
        public enum ServerPackets
        {
            SAlertMsg,
            SKeyPair,
            SLoginOK,
            SPlayerChars,
            SJobData,
            SInGame,
            SPlayerInv,
            SPlayerInvUpdate,
            SPlayerWornEq,
            SPlayerHP,
            SPlayerSP,
            SPlayerStats,
            SPlayerData,
            SPlayerMove,
            SNPCMove,
            SPlayerDir,
            SNPCDir,
            SPlayerXY,
            SAttack,
            SNPCAttack,
            SCheckForMap,
            SMapData,
            SMapNPCData,
            SMapNPCUpdate,
            SGlobalMsg,
            SAdminMsg,
            SPlayerMsg,
            SMapMsg,
            SSpawnItem,
            SItemEditor,
            SUpdateItem,
            SSpawnNPC,
            SNPCDead,
            SNPCEditor,
            SUpdateNPC,
            SEditMap,
            SShopEditor,
            SUpdateShop,
            SSkillEditor,
            SUpdateSkill,
            SSkills,
            SLeftMap,
            SSendPing,
            SActionMsg,
            SPlayerEXP,
            SBlood,
            SAnimationEditor,
            SUpdateAnimation,
            SAnimation,
            SMapNPCVitals,
            SCooldown,
            SClearSkillBuffer,
            SSayMsg,
            SOpenShop,
            SResetShopAction,
            SStunned,
            SMapWornEq,
            SBank,
            SLeftGame,
            STradeInvite,
            STrade,
            SCloseTrade,
            STradeUpdate,
            STradeStatus,
            SMapReport,
            STarget,
            SAdmin,
            SMapNames,
            SCritical,
            SrClick,
            SHotbar,
            SSpawnEvent,
            SEventMove,
            SEventDir,
            SEventChat,
            SEventStart,
            SEventEnd,
            SPlayBGM,
            SPlaySound,
            SFadeoutBGM,
            SStopSound,
            SSwitchesAndVariables,
            SMapEventData,
            SChatBubble,
            SSpecialEffect,
            SPic,
            SHoldPlayer,
            SEmote,
            SPartyInvite,
            SPartyUpdate,
            SPartyVitals,

            STime,
            SClock,

            Count
        }

    }
}